version: '3'
services:
  nginx:
    build: ./config/nginx
    links:
      - balancer
      - static
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - variables.env
    restart: unless-stopped
  balancer:
    image: dockercloud/haproxy
    links:
      - node1
      - node2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "80"
    restart: unless-stopped
  node1:
    build: .
    expose:
     - "3001"
    env_file:
     - variables.env
    restart: unless-stopped
  node2:
    build: .
    expose:
     - "3001"
    env_file:
     - variables.env
    restart: unless-stopped
  static:
    build: .
    expose:
     - "3001"
    restart: unless-stopped